# Generated by Django 4.2.10 on 2024-02-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='designation',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
